name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gembcior/d-ral-docker

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        echo ${{github.workspace}}
        ls -al
        pwd
